

# used to standardise extensions used
DEFAULT_CODE_EXTENSION = 	 '.byte'
DEFAULT_ASSEMBLY_EXTENSION = '.ass'
DEFAULT_COMPILED_EXTENSION = '.hex'
DEFAULT_TOKENS_EXTENSION = 	 '.tokens'
DEFAULT_TEST_RESULT_EXTENSION = '.expected'